(define a "fds")
;(define b (lambda (x) (lambda (y) (+ y x))))
;(define c (b 2))
;(display (boolean? 3))
(display (+ 2 3) a)
;(display (c 5))
;(display (car (cdr (cons 4 '(1 2)))))
;
(define ff (call/cc (lambda (cc)
                    (lambda (x)
                              (display "cc")
                              (cc x)))))

(if (procedure? ff)
          (ff 4)
          (display ff))